### ISSUE TITLE
Datapoint on line chart is being connected in wrong sequence.

### ISSUE THREAD

**Issue by Sutikshan** [openmhealth/web-visualizations#1]
Hi Team,
I am using web-visualizations library, and drawing reading of different parameters in my web-application, named as ehrdiary.
We are facing an issue, even though I make sure, I am supplying sorted data array, graph is being drawn with lines connected haphazardly as shown in this screen-shot. What could be the reason ? We simply what them to be connected in chronological order as shown in example on github page.
![screenshot from 2015-09-07 13 22 20](https://cloud.githubusercontent.com/assets/1274910/9711738/8a95c16a-5563-11e5-9872-006239dd3a80.png)

**Comment by emersonf** [comment]
@Sutikshan, can you provide that data so that we can test on our side? If so, please create a JSON Gist and send us the link.

**Comment by Sutikshan** [comment]
I just upgraded to 1.10 of plottableJS, and it fixed this issue (including couple of other.).
~Thanks. you guys have  created a cool library for the purpose of health-data.

**Comment by emersonf** [comment]
@jasperSpeicher guess we should bump the dependency in Bower and regression test then.
