### ISSUE TITLE
Issues getting running

### ISSUE THREAD

**Issue by salinsde** [openmhealth/web-visualizations#10]
Hi Team,

I am having issues getting the example running.  I was able to successfully get everything running until 5.  I am able to get gulp running.  But here is the following error output.

dsalins:web-visualizations dsalins$ gulp
[11:21:19] Using gulpfile ~/Documents/SVNRepositories/Stanford_Wearables/web-visualizations/gulpfile.js
[11:21:19] Starting 'clean'...
[11:21:19] Finished 'clean' after 21 ms
[11:21:19] Starting 'default'...
[11:21:19] Starting 'generate-component-styles'...
[11:21:19] Starting 'generate-concatenated-styles'...
[11:21:19] Starting 'generate-component-scripts'...
[11:21:19] Starting 'generate-concatenated-script'...
[11:21:19] Finished 'default' after 57 ms
src/charts.js: line 460, col 9, 'xScale' was used before it was defined.
src/charts.js: line 461, col 9, 'yScale' was used before it was defined.
src/charts.js: line 462, col 9, 'yScaleCallback' was used before it was defined.
src/charts.js: line 468, col 9, 'xAxis' was used before it was defined.
src/charts.js: line 472, col 9, 'yAxis' was used before it was defined.
src/charts.js: line 474, col 9, 'yLabel' was used before it was defined.
src/charts.js: line 480, col 9, 'drag' was used before it was defined.
src/charts.js: line 488, col 9, 'wheelCallback' was used before it was defined.
src/charts.js: line 495, col 9, 'plots' was used before it was defined.
src/charts.js: line 515, col 9, 'pointPlot' was used before it was defined.
src/charts.js: line 531, col 9, 'secondaryYAxes' was used before it was defined.
src/charts.js: line 672, col 9, 'colorScale' was used before it was defined.
src/charts.js: line 673, col 9, 'legend' was used before it was defined.
src/charts.js: line 712, col 11, 'hidePanZoomHint' was used before it was defined.
src/charts.js: line 750, col 9, 'pzi' was used before it was defined.
src/charts.js: line 751, col 9, 'pziXAxis' was used before it was defined.
src/charts.js: line 850, col 9, 'clearZoomLevelButtonActiveStates' was used before it was defined.
src/charts.js: line 854, col 9, 'toolbar' was used before it was defined.
src/charts.js: line 963, col 11, 'showHoverPointTooltip' was used before it was defined.
src/charts.js: line 996, col 11, 'pointer' was used before it was defined.
src/charts.js: line 1004, col 11, 'pointerMove' was used before it was defined.
src/charts.js: line 1046, col 11, 'tip' was used before it was defined.

22 errors
src/charts.js: line 460, col 9, 'xScale' was used before it was defined.
src/charts.js: line 461, col 9, 'yScale' was used before it was defined.
src/charts.js: line 462, col 9, 'yScaleCallback' was used before it was defined.
src/charts.js: line 468, col 9, 'xAxis' was used before it was defined.
src/charts.js: line 472, col 9, 'yAxis' was used before it was defined.
src/charts.js: line 474, col 9, 'yLabel' was used before it was defined.
src/charts.js: line 480, col 9, 'drag' was used before it was defined.
src/charts.js: line 488, col 9, 'wheelCallback' was used before it was defined.
src/charts.js: line 495, col 9, 'plots' was used before it was defined.
src/charts.js: line 515, col 9, 'pointPlot' was used before it was defined.
src/charts.js: line 531, col 9, 'secondaryYAxes' was used before it was defined.
src/charts.js: line 672, col 9, 'colorScale' was used before it was defined.
src/charts.js: line 673, col 9, 'legend' was used before it was defined.
src/charts.js: line 712, col 11, 'hidePanZoomHint' was used before it was defined.
src/charts.js: line 750, col 9, 'pzi' was used before it was defined.
src/charts.js: line 751, col 9, 'pziXAxis' was used before it was defined.
src/charts.js: line 850, col 9, 'clearZoomLevelButtonActiveStates' was used before it was defined.
src/charts.js: line 854, col 9, 'toolbar' was used before it was defined.
src/charts.js: line 963, col 11, 'showHoverPointTooltip' was used before it was defined.
src/charts.js: line 996, col 11, 'pointer' was used before it was defined.
src/charts.js: line 1004, col 11, 'pointerMove' was used before it was defined.
src/charts.js: line 1046, col 11, 'tip' was used before it was defined.

22 errors
[11:21:21] gulp-notify: [Gulp notification] Scripts copy task complete
[11:21:21] Finished 'generate-component-scripts' after 1.36 s
[11:21:21] gulp-notify: [Gulp notification] Scripts concat task complete
[11:21:21] Finished 'generate-concatenated-script' after 1.36 s
[11:21:21] gulp-notify: [Gulp notification] Concatenated styles task complete
[11:21:21] Finished 'generate-concatenated-styles' after 1.39 s
[11:21:21] gulp-notify: [Gulp notification] Component styles task complete
[11:21:21] Finished 'generate-component-styles' after 1.43 s
dsalins:web-visualizations dsalins$ 

Then I open the example/charts.html and the data does not load. 

Please advise.

**Comment by jasperSpeicher** [comment]
Hi Denis,
Glad to see that you are trying out the library. What version of the source did you download? was it the master branch? Develop? A release?
Thank you,
Jasper

**Comment by jasperSpeicher** [comment]
If you are just running the chart example from your file system, you will get a CORS error when it tries to load the json. You can fix this by running `gulp watch` and visiting:

[http://localhost:8080/examples/charts.html](http://localhost:8080/examples/charts.html)

Does that help?

Thanks,
Jasper

**Comment by salinsde** [comment]
Awesome.  Thank you for that help.

If I could advise, to add that part in the readme tutorial also.  That
resolved my issue.

thanks.
-Denis

On Wed, Feb 17, 2016 at 12:39 PM, Jasper Speicher notifications@github.com
wrote:

> If you are just running the chart example from your file system, you will
> get a CORS error when it tries to load the json. You can fix this by
> running gulp watch and visiting http://localhost:8080/examples/charts.html
> 
> Does that help?
> 
> Thanks,
> Jasper
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openmhealth/web-visualizations/issues/10#issuecomment-185393566
> .

## 

Denis N. Salins
Cell: (954) 214-1456
salins.denis@gmail.com
http://about.me/Denis.Salins
