### ISSUE TITLE
The jsfiddle seems to be broken (Uncaught TypeError: defaultStyles.concat is not a function)

### ISSUE THREAD

**Issue by x12a1f** [openmhealth/web-visualizations#12]
When I try the fiddle at http://jsfiddle.net/jasperspeicher/dremvboo/ I get an `Uncaught TypeError: defaultStyles.concat is not a function`

It used to work a couple of days/weeks? ago. What has changed?

**Comment by jasperSpeicher** [comment]
Thanks! Looking into it...

**Comment by jasperSpeicher** [comment]
Ok, pushed some changes that appear to fix the issue. Please let me know if that works out for you!

**Comment by jasperSpeicher** [comment]
Changes are available on master and develop.

**Comment by jasperSpeicher** [comment]
Note: we just updated the fiddle code to better match the documentation on git and in the example file. Hope that helps!
