### ISSUE TITLE
Error when no default style

### ISSUE THREAD

**Issue by jaredsieling** [openmhealth/web-visualizations#17]
When no default style is found, an error is being thrown because it returns an empty object instead of an empty array.  Code is [here](https://github.com/openmhealth/web-visualizations/blob/master/src/ChartStyles.js#L451), and the return type should be changed to an empty array.

**Comment by jasperSpeicher** [comment]
Closed by 7b7dc3508a1706fef02f8dbdec9169e09f3abd3b
