### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by tleguijt** [openmhealth/web-visualizations#2]
We are developing an app for which we'd like to use the web-visualization library.
But to keep the footprint of the app as small as possible it would be better to have the least amount of extra libraries in order to use the graph-lib.
Since this lib and plottable rely on D3, and D3 ships with a lot of DOM-manipulation functionality, it would be better to not use jQuery for the things we can use D3 for.

**Comment by jasperSpeicher** [comment]
Closed by release v1.2.0
