### ISSUE TITLE
Making yAxis optional and showing label for threshold values only

### ISSUE THREAD

**Issue by Sutikshan** [openmhealth/web-visualizations#6]
Hi Team,
To show charts on mobile devices properly, I think yAxis can be made optional with following code changes 

 var yAxisGroup = new Plottable.Components.Group([yAxis, yLabel]);

```
var topRow;
if (options.showYAxis) {
  topRow = [yAxisGroup, plotGroup];
} else {
  topRow = [null, plotGroup];
}
```

But when we do so,it becomes important to show label text at least for threshold values, I am not able to place the label text exactly at place of Y axis threshold value, is it someway possible. (I edited following image with label text using paintbrush...)

![screen shot 2015-12-18 at 11 51 22 am 1](https://cloud.githubusercontent.com/assets/1274910/11895580/11b20554-a5a6-11e5-831f-245b3c495ac5.png)

**Comment by jasperSpeicher** [comment]
Hi @Sutikshan 

I think both should be possible without too much trouble.

Shortly after we released the lib, Plottable added some new ways of plotting grid lines http://plottablejs.org/examples/tick-generator/

We will look into refactoring the threshold lines so that we can get those labels for free.
How does that sound?

Thank you,
Jasper

**Comment by Sutikshan** [comment]
Thanks Jasper,
I have not updated to latest version. Let me do that, and if you are okay to bring this change, I will also try from my side. I hope you found that removal of yAxis is desired for chart in narrow width mobile devices.

**Comment by jasperSpeicher** [comment]
No problem. I made the changes to the development branch last night. I am going to create a release later today, along with some additions to the readme. If you decide to pull in the dev branch before I release, check charts.html in the examples directory to see the configuration options that affect the axes' visibility.

**Comment by jasperSpeicher** [comment]
Ok, see release v1.2.1!
